development:
  adapter: postgresql
  encoding: unicode
  database: chloroform_development
  pool: 5
  username: dave

test:
  adapter: postgresql
  encoding: unicode
  database: chloroform_test
  pool: 5
  username: dave

production:
  adapter: postgresql
  encoding: unicode
  database: chloroform_production
  pool: 5
  username: dave